version: '3.8'

services:
  redis-ephemeral:
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru

  redis-audit:
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru